name: Check code style
on: [push, pull_request]
jobs:
  golint:
    name: runner / golint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: './...'
